apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
#- ./cluster-role.yaml
#- ./cluster-role-binding.yaml
- ./service-account.yaml
- ./deployment.yaml
- ./service.yaml

namespace: provisioning-system

commonLabels:
  app.kubernetes.io/name: provisioning
  app.kubernetes.io/instance: provisioning