version: "3.9"
services:

  web:
    image: testcalvinverse.azurecr.io/service-provisioning-ui-web:0.2.0-alpha.18
    labels:
      SERVICE_NAME: web
    ports:
      - "8080"


  controller:
    image: testcalvinverse.azurecr.io/service-provisioning-controller:0.2.0-alpha.65
    labels:
      SERVICE_NAME: controller
    ports:
      - "8090"


  database:
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    image: arangodb:3.8
    labels:
      SERVICE_NAME: database
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container: